# Timeout in seconds that Limine will use before automatically booting.
timeout: 5

# The entry name that will be displayed in the boot menu.
/froggy-os
    # We use the Limine boot protocol.
    protocol: limine
    resolution: 640x480
    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/kernel
    module_path: boot():/boot/zap-light16.psf
    module_path: boot():/boot/zap-vga16.psf
